# Generated by Django 4.0.6 on 2022-07-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="landline_number",
            field=models.CharField(
                blank=True,
                help_text="Landline Number of the business.",
                max_length=255,
                null=True,
                verbose_name="Landline Number",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="mobile_number",
            field=models.CharField(
                default=123,
                help_text="Mobile Number of the business.",
                max_length=255,
                verbose_name="Mobile Number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile Number of the customer.",
                max_length=255,
                null=True,
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="PAN Number of the customer.",
                max_length=255,
                null=True,
                verbose_name="PAN Number",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="address",
            field=models.CharField(
                help_text="Address of the business where it is located.",
                max_length=255,
                verbose_name="Business Address",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="gst_number",
            field=models.CharField(
                help_text="GST Number of the business.",
                max_length=255,
                verbose_name="GST Number",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(
                help_text="Name of the business",
                max_length=255,
                unique=True,
                verbose_name="Business Name",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                help_text="Address of the customer.",
                max_length=255,
                verbose_name="Customer Address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="business",
            field=models.ForeignKey(
                help_text="Business of the customer.",
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.business",
                verbose_name="Business",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(
                help_text="GST Number of the customer.",
                max_length=255,
                verbose_name="GST Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                help_text="Name of the customer",
                max_length=255,
                verbose_name="Customer Name",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="business",
            field=models.ForeignKey(
                help_text="Business of the invoice.",
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.business",
                verbose_name="Business",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer of the invoice.",
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                help_text="Invoice Number of the invoice.",
                max_length=255,
                verbose_name="Invoice Number",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="line_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Line Items of the invoice.",
                to="billing.lineitem",
                verbose_name="Line Items",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Total Amount of the invoice.",
                max_digits=12,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Amount of the product.",
                max_digits=12,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="cgst",
            field=models.DecimalField(
                decimal_places=3,
                help_text="CGST of the product.",
                max_digits=10,
                verbose_name="CGST",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer of the line item.",
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="hsn_code",
            field=models.CharField(
                help_text="HSN Code of the product.",
                max_length=255,
                verbose_name="HSN Code",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="product_name",
            field=models.CharField(
                help_text="Name of the product.",
                max_length=255,
                verbose_name="Product Name",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Quantity of the product.",
                max_digits=10,
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="rate",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Rate of the product.",
                max_digits=12,
                verbose_name="Rate",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="sgst",
            field=models.DecimalField(
                decimal_places=3,
                help_text="SGST of the product.",
                max_digits=10,
                verbose_name="SGST",
            ),
        ),
    ]
