# Generated by Django 4.0.6 on 2022-09-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_business_landline_number_business_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Business", "verbose_name_plural": "Businesses"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile Number of the customer.",
                max_length=12,
                null=True,
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="PAN Number of the customer.",
                max_length=10,
                null=True,
                verbose_name="PAN Number",
            ),
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="line_items",
        ),
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=models.ForeignKey(
                blank=True,
                default=1,
                help_text="Line Items of the invoice.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="billing.lineitem",
                verbose_name="Line Items",
            ),
            preserve_default=False,
        ),
    ]
