# Generated by Django 4.0.6 on 2022-10-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_remove_customer_business_customer_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="business",
            new_name="businesses",
        ),
    ]
