# Generated by Django 4.0.6 on 2022-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_rename_business_customer_businesses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Address of the customer.",
                max_length=255,
                null=True,
                verbose_name="Customer Address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(
                blank=True,
                help_text="GST Number of the customer.",
                max_length=255,
                null=True,
                verbose_name="GST Number",
            ),
        ),
    ]
