# Generated by Django 4.0.6 on 2022-11-10 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_alter_customer_address_alter_customer_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date at which invoice was raised.",
            ),
            preserve_default=False,
        ),
    ]
