# Generated by Django 4.0.6 on 2023-01-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_invoice_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                help_text="Name of the customer",
                max_length=255,
                unique=True,
                verbose_name="Customer Name",
            ),
        ),
    ]
