# Generated by Django 4.0.6 on 2023-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_lineitem_gst_tax_rate_lineitem_igst_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="type_of_invoice",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")],
                default="sell",
                help_text="Type of Invoice.",
                max_length=255,
                verbose_name="Type of Invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="type_of_invoice",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")],
                default="sell",
                help_text="Type of Invoice.",
                max_length=255,
                verbose_name="Type of Invoice",
            ),
        ),
    ]
