# Generated by Django 4.0.6 on 2023-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_historicalinvoice_type_of_invoice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="landline_number",
        ),
        migrations.AddField(
            model_name="business",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="Bank Account Number of the business.",
                max_length=255,
                null=True,
                verbose_name="A/c. No.",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="bank_branch_name",
            field=models.CharField(
                blank=True,
                help_text="Branch Name of the Bank Account.",
                max_length=255,
                null=True,
                verbose_name="Branch Name",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="bank_ifsc_code",
            field=models.CharField(
                blank=True,
                help_text="IFSC Code of the Bank Account.",
                max_length=255,
                null=True,
                verbose_name="IFSC Code",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Bank Name of the business.",
                max_length=255,
                null=True,
                verbose_name="Bank Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="type_of_invoice",
            field=models.CharField(
                choices=[("inward", "Inward"), ("outward", "Outward")],
                default="inward",
                help_text="Type of Invoice.",
                max_length=255,
                verbose_name="Type of Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type_of_invoice",
            field=models.CharField(
                choices=[("inward", "Inward"), ("outward", "Outward")],
                default="inward",
                help_text="Type of Invoice.",
                max_length=255,
                verbose_name="Type of Invoice",
            ),
        ),
    ]
