# Generated by Django 4.0.6 on 2023-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_remove_business_landline_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="PAN Number of the business.",
                max_length=10,
                null=True,
                verbose_name="PAN Number",
            ),
        ),
    ]
