# Generated by Django 4.2.2 on 2023-06-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_business_state_name_customer_state_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="primary_color_theme",
            field=models.CharField(
                default="#d04e00",
                help_text="Primary Color Theme of the business.",
                max_length=15,
                verbose_name="Primary Color Theme",
            ),
        ),
    ]
