# Generated by Django 4.2.2 on 2023-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_business_primary_color_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the product",
                        max_length=255,
                        unique=True,
                        verbose_name="Product Name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
