# Generated by Django 4.2.2 on 2023-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_alter_historicalinvoice_type_of_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(
                default=711319,
                help_text="HSN Code of the product.",
                max_length=255,
                verbose_name="HSN Code",
            ),
        ),
    ]
