# Generated by Django 4.2.2 on 2023-12-04 18:50

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_product_hsn_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_tax_rate",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.03"),
                help_text="GST Tax Rate of the product.",
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
                verbose_name="GST Tax Rate",
            ),
        ),
    ]
