# Generated by Django 4.2.2 on 2025-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_product_gst_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("gm", "Gram (g)"),
                    ("kg", "Kilogram (kg)"),
                    ("pcs", "Units (pcs)"),
                ],
                default="gm",
                help_text="Unit for quantity and rate (e.g., gm, kg, pcs).",
                max_length=10,
                verbose_name="Unit",
            ),
        ),
    ]
