# Generated by Django 4.2.2 on 2026-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_add_workspace_id_to_abstract_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Authorised signatory signature for invoices.', null=True, upload_to='signatures/', verbose_name='Signature Image'),
        ),
    ]
