# Generated by Django 4.2.2 on 2025-11-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_add_unit_textchoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_unit",
            field=models.CharField(
                choices=[
                    ("gm", "Gram (g)"),
                    ("kg", "Kilogram (kg)"),
                    ("pcs", "Units (pcs)"),
                ],
                default="gm",
                help_text="Default unit for this product (e.g., gm, kg, pcs).",
                max_length=10,
                verbose_name="Default Unit",
            ),
        ),
    ]
