# Generated by Django 4.2.2 on 2026-04-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0023_lineitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(blank=True, default='gms', help_text='Unit of measurement (e.g., gms, pcs, kg, nos, etc.)', max_length=20, verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('entity', models.CharField(choices=[('invoice', 'Invoice'), ('customer', 'Customer'), ('product', 'Product'), ('business', 'Business')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='billing_aud_entity_bd4e7d_idx'), models.Index(fields=['action'], name='billing_aud_action_3cf73d_idx')],
            },
        ),
    ]
