# Generated by Django 4.2.2 on 2026-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_lineitem_unit_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('imported', 'Imported'), ('printed', 'Printed'), ('exported', 'Exported'), ('merged', 'Merged')], max_length=10),
        ),
    ]
