# Generated by Django 4.2.2 on 2026-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_business_email_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for invoice numbers (e.g. SGJ, LJ). Leave blank for plain numbers.', max_length=20, verbose_name='Invoice Prefix'),
        ),
    ]
