# Generated by Django 4.2.2 on 2026-04-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_business_invoice_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='distance_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance (KM)'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='E-way Bill Number'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('Road', 'Road'), ('Rail', 'Rail'), ('Air', 'Air'), ('Ship', 'Ship')], default='Road', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='transporter_gstin',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Transporter GSTIN'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='transporter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transporter Name'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Vehicle Number'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('ODC', 'Over Dimensional Cargo')], default='Regular', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='distance_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance (KM)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='E-way Bill Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('Road', 'Road'), ('Rail', 'Rail'), ('Air', 'Air'), ('Ship', 'Ship')], default='Road', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transporter_gstin',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Transporter GSTIN'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transporter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transporter Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Vehicle Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('ODC', 'Over Dimensional Cargo')], default='Regular', max_length=10),
        ),
    ]
