# Generated by Django 4.2.2 on 2026-05-09 18:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_historicalinvoice_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITCReclaimLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.IntegerField(default=1)),
                ('opening_cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening reclaimable CGST balance (cumulative 4(B)(2) reversals not yet reclaimed).', max_digits=14)),
                ('opening_sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening reclaimable SGST balance.', max_digits=14)),
                ('opening_igst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening reclaimable IGST balance.', max_digits=14)),
                ('opening_as_of', models.DateField(blank=True, help_text='Date the opening balance was last set / amended (for audit trail).', null=True)),
                ('business', models.OneToOneField(help_text='Business this ledger belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='itc_reclaim_ledger', to='billing.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
