# Generated by Django 4.2.2 on 2026-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_itcreclaimledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='source_file',
            field=models.TextField(blank=True, help_text='Original invoice image/PDF (audit trail for AI imports).', max_length=100, null=True, verbose_name='Source File'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_file',
            field=models.FileField(blank=True, help_text='Original invoice image/PDF (audit trail for AI imports).', null=True, upload_to='invoice_sources/%Y/%m/', verbose_name='Source File'),
        ),
    ]
