# Generated by Django 4.2.2 on 2026-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_historicalinvoice_source_file_invoice_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='source_preview',
            field=models.TextField(blank=True, help_text='JPEG preview of source_file for in-browser display.', max_length=100, null=True, verbose_name='Source Preview'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_preview',
            field=models.ImageField(blank=True, help_text='JPEG preview of source_file for in-browser display.', null=True, upload_to='invoice_sources/%Y/%m/previews/', verbose_name='Source Preview'),
        ),
    ]
