# Generated by Django 5.2.17 on 2026-08-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_filedperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.IntegerField(default=1)),
                ('image', models.FileField(help_text='The photographed supplier bill.', upload_to='inward_captures/%Y/%m/')),
                ('supplier_hint', models.CharField(blank=True, default='', help_text='Optional supplier name jotted at capture time.', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('converted', 'Converted')], default='new', max_length=12)),
                ('business', models.ForeignKey(blank=True, help_text='Best guess at the buying firm; confirmed at conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.business')),
                ('invoice', models.ForeignKey(blank=True, help_text='The inward invoice this capture became.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
