# Generated by Django 5.2.17 on 2026-10-07 07:14

# State-only: Django enforces on_delete itself, so this changes no table.
# `manage.py sqlmigrate billing 0041` prints "(no-op)" on Postgres (H6).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0040_protect_invoice_parties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="customer",
            field=models.ForeignKey(help_text="Customer of the line item.", on_delete=django.db.models.deletion.PROTECT, to="billing.customer", verbose_name="Customer"),
        ),
    ]
