# Generated by Django 5.2.18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0042_v3_role_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="cancel_reason",
            field=models.CharField(blank=True, db_default="", default="", max_length=255),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="cancelled_by",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="replaces",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="status",
            field=models.CharField(choices=[("active", "Active"), ("cancelled", "Cancelled")], db_default="active", db_index=True, default="active", help_text="Active, or cancelled: a cancelled bill keeps its number but counts in no figure.", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancel_reason",
            field=models.CharField(blank=True, db_default="", default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancelled_by",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="invoice",
            name="replaces",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(choices=[("active", "Active"), ("cancelled", "Cancelled")], db_default="active", db_index=True, default="active", help_text="Active, or cancelled: a cancelled bill keeps its number but counts in no figure.", max_length=10),
        ),
    ]
