# Generated by Django 5.2.18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0043_v3_bill_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinnedInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_id", models.IntegerField(db_index=True)),
                ("invoice_number", models.CharField(blank=True, db_default="", default="", max_length=255)),
                ("invoice_date", models.DateField()),
                ("type_of_invoice", models.CharField(choices=[("outward", "Outward"), ("inward", "Inward")], db_default="outward", default="outward", max_length=255)),
                ("total_amount", models.DecimalField(db_default=0, decimal_places=3, default=0, max_digits=12)),
                ("kind", models.CharField(choices=[("deleted", "Deleted"), ("cancelled", "Cancelled, set aside for v2")], db_default="deleted", default="deleted", max_length=10)),
                ("reason", models.CharField(blank=True, db_default="", default="", max_length=255)),
                ("data", models.JSONField(default=dict, help_text="Every field of the bill and its lines, as text.")),
                ("audit_log_id", models.IntegerField(blank=True, help_text="The v2-shaped 'deleted' audit row.", null=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("business", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="billing.business")),
                ("customer", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="billing.customer")),
                ("deleted_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("restored_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-deleted_at", "-id"],
                "indexes": [models.Index(fields=["business", "invoice_date"], name="billing_bin_busines_338614_idx")],
            },
        ),
    ]
