# Generated by Django 5.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0044_v3_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, db_default="", default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(blank=True, choices=[("walkin", "Walk-in"), ("person", "Person"), ("business", "Business")], db_default="", default="", help_text="Walk-in (the counter's record for cash sales without a name), person or business.", max_length=10),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="sent_count",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="sent_to",
            field=models.CharField(blank=True, db_default="", default="", max_length=15),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="sent_via",
            field=models.CharField(blank=True, choices=[("whatsapp", "WhatsApp"), ("share", "Share sheet")], db_default="", default="", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_count",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_to",
            field=models.CharField(blank=True, db_default="", default="", max_length=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_via",
            field=models.CharField(blank=True, choices=[("whatsapp", "WhatsApp"), ("share", "Share sheet")], db_default="", default="", max_length=10),
        ),
    ]
