repos:
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.10.0
  hooks:
    - id: ruff
      language_version: python3
      args: [ --fix, --exit-non-zero-on-fix ]