# Same as Black.
line-length = 120

# Assume Python 3.10.
target-version = "py310"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[lint]
# Enable rules by default
select = [
    "E", "F", "I", "ICN", "TID",
    "UP", "W", "SIM", "B", "A", "TRY",
    "Q", "COM", "PERF", "RUF", "PGH",
    "ISC"
]

ignore = [
    "E501",  # Line too long
    "F403",  # 'from module import *' used
    "E402",  # Module level import not at top of file
    "E401",  # Multiple imports on one line
    "UP026", # Deprecated unittest assertion
    "UP032", # Use f-string instead of format call
    "UP030", # Format string-like object with f-string
    "SIM102", # Use a single if statement instead of nested if statements
    "SIM222", # Use str.format instead of % formatting
    "SIM114", # Combine if branches using logical or
    "SIM115", # Use context handler for opening files
    "B904",   # Within an except clause, raise exceptions with raise ... from err
    "COM812", # Missing trailing comma
    "TRY002", # Create your own exception
    "TRY003", # Avoid specifying long messages outside the exception class
    "TRY401", # Redundant exception handler
    "TRY201", # Use exception blocks for handling exceptions
    "TRY301", # Raise specific exceptions
    "TRY400", # Use logger.exception for exception logging
    "A003",   # Class attribute shadowing built-in
    "RUF012", # Mutable class attributes should be annotated with typing.ClassVar
    "RUF005", # Consider iterable unpacking instead of concatenation
    "PERF401", # Use a list comprehension instead of a for-loop
    "PERF203", # Try using set comprehension instead of list comprehension
    "RUF015"  # Prefer next() over iteration
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10 