from decimal import Decimal

BILLING_DECIMAL_PLACE_PRECISION = 3
GST_TAX_RATE = Decimal("0.03")
HSN_CODE = 711319

PAGINATION_PAGE_SIZE = 15

INVOICE_TYPE_BUY = "buy"
INVOICE_TYPE_SELL = "sell"
INVOICE_TYPE_CHOICES = (
    (INVOICE_TYPE_BUY, "Buy"),
    (INVOICE_TYPE_SELL, "Sell"),
)
