"""
Django settings for gst_billing project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# `local.py` holds dev secrets and is gitignored. In CI / fresh checkouts it
# may not exist — fall back to env vars so settings can still load. The
# fallback never picks an insecure default in non-DEBUG environments: if
# DJANGO_SECRET_KEY is unset and DEBUG isn't truthy, we raise so a misconfigured
# deploy fails loudly instead of running with a known key.
try:
    from gst_billing import local  # type: ignore[attr-defined]
except ImportError:
    _env_key = os.environ.get("DJANGO_SECRET_KEY")
    _debug_env = os.environ.get("DEBUG", "").lower() in ("1", "true", "yes")
    if not _env_key and not _debug_env:
        raise RuntimeError(
            "gst_billing/local.py is missing and DJANGO_SECRET_KEY is not set. "
            "Set DJANGO_SECRET_KEY (or create local.py) before starting Django "
            "in a non-DEBUG environment."
        )

    class _LocalShim:
        SECRET_KEY = _env_key or "django-insecure-dev-only"
        DATABASES = None
    local = _LocalShim()  # type: ignore[assignment]

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = local.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.68.111", "*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "billing",
    "explorer",
    "simple_history",
    "rest_framework",
    # Stores rotated-out refresh tokens so they die on rotation.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "cacheops",
]

MIDDLEWARE = [
    # GZip first so it compresses everything below. Per Django docs the
    # gzip middleware is safe even with auth — modern browsers + JWT
    # don't expose the BREACH attack surface that originally made gzip
    # over auth'd HTML risky. JSON responses from this app are the
    # heaviest items on the wire (gst_summary can be ~80 KB raw, 12 KB
    # gzipped). Single-line config, ~80% payload reduction.
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware should be placed before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",  # Removed CSRF middleware since we're using JWT authentication
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "gst_billing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "gst_billing.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
# Database selection is explicit, env-driven, and defaults to the SAFE branch:
#   (unset)                        -> local.DATABASES_DEV (or legacy DATABASES)
#   GST_DB=prod                    -> refuses unless GST_ALLOW_PROD=1 is also set
#   GST_DB=prod GST_ALLOW_PROD=1   -> local.DATABASES_PROD, with a loud banner
# Production containers never reach this code — they run production_settings.py
# with env-provided DB_* — so this gate exists purely to keep a local
# runserver/migrate/shell away from the real books by accident.
_db_choice = os.environ.get("GST_DB", "dev").lower()
_dev_db = getattr(local, "DATABASES_DEV", None) or getattr(local, "DATABASES", None)
_prod_db = getattr(local, "DATABASES_PROD", None)

if _db_choice == "prod":
    if os.environ.get("GST_ALLOW_PROD") != "1":
        raise RuntimeError(
            "GST_DB=prod refused: set GST_ALLOW_PROD=1 as well to confirm you "
            "really want local commands pointed at the PRODUCTION database."
        )
    if not _prod_db:
        raise RuntimeError("GST_DB=prod but local.py defines no DATABASES_PROD.")
    print("\n*** WARNING: connected to the PRODUCTION database (REAL DATA). ***\n")
    DATABASES = _prod_db
elif _dev_db:
    DATABASES = _dev_db
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Same-origin framing must be allowed: the Inward Bills detail page renders the
# stored bill in an <iframe src="/media/…">. Django's default is DENY, which the
# browser applies to the media response in DEBUG (where Django serves /media/
# itself) and blocks the viewer. SAMEORIGIN still blocks cross-origin framing,
# which is the clickjacking threat we actually care about.
X_FRAME_OPTIONS = "SAMEORIGIN"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EXPLORER_CONNECTIONS = {"Default": "default"}
EXPLORER_DEFAULT_CONNECTION = "default"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 15,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        # Scoped rates for the unauthenticated token endpoints (billing.api.auth).
        # 10 login attempts/min per IP stops naive brute force without ever
        # touching a human; refresh is authenticated-adjacent and more frequent.
        "login": "10/min",
        "token_refresh": "60/min",
    },
    "DEFAULT_RENDERER_CLASSES": (
        [
            "rest_framework.renderers.JSONRenderer",
        ]
        if not DEBUG
        else [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",
        ]
    ),
    # JWT Authentication only
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    # 12h access / 30d refresh with rotation + blacklist — was 30d/180d static,
    # which meant a leaked localStorage token worked for a month and a stolen
    # refresh for six. The SPA refreshes transparently on 401 (api.ts), so
    # shorter lifetimes cost the user nothing.
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development
CORS_ALLOWED_ORIGINS = (
    [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    if not DEBUG
    else []
)

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None)

if REDIS_PASSWORD:
    # Cacheops configuration
    CACHEOPS_REDIS = {
        "host": os.getenv("REDIS_HOST", "localhost"),  # Redis server host
        "port": 6379,  # Redis server port
        "db": 0,  # Redis database number
        "socket_timeout": 3,  # Connection timeout in seconds
        "password": os.getenv("REDIS_PASSWORD", None),  # Redis password (optional)
        "ssl": True,
    }

    print(f"Using Redis with password: {CACHEOPS_REDIS=}")

    CACHEOPS_DEFAULTS = {
        "timeout": 60 * 15,  # 15 minutes default cache timeout
        "cache_on_save": True,  # Cache objects automatically when they are saved
        "invalidate_on_save": True,  # Invalidate related caches when objects are saved
    }

    ONE_HOUR = 60 * 60
    ONE_DAY = 60 * 60 * 24

    # Register models for caching
    CACHEOPS = {
        # Cache all Business models queries for 1 day
        "billing.Business": {"ops": "all", "timeout": ONE_DAY},
        # Cache all Customer models queries for 1 day
        "billing.Customer": {"ops": "all", "timeout": ONE_DAY},
        # Cache all Product models queries for 1 day
        "billing.Product": {"ops": "all", "timeout": ONE_DAY},
        # Cache all Invoice models queries for 1 hour
        "billing.Invoice": {"ops": "all", "timeout": ONE_HOUR},
        # Cache all LineItem models queries for 1 hour
        "billing.LineItem": {"ops": "all", "timeout": ONE_HOUR},
    }

# AI Configuration
# Active extractor: Google Gemini (billing.utils.AIInvoiceProcessor).
# Free key at https://aistudio.google.com/apikey. The model is
# overridable for A/B testing — Gemini 2.5 Flash is the free-tier
# sweet spot, Pro is paid + slower but more accurate on tough scans.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
# Multi-key rotation: comma-separated list of Gemini keys. The
# extractor tries each in order, marks 429'd keys as cooled down for
# the retry-after window suggested by the API, and skips them on
# subsequent calls. Effectively multiplies the free-tier daily cap
# (20/day on flash-lite) by the number of keys. Keys can come from
# different Google accounts — each has its own quota.
# Backward compat: single GEMINI_API_KEY is appended to this list if
# both are set.
# GSTIN taxpayer lookup (billing/gstin.py). Without a key the endpoint still
# validates the checksum and derives state + PAN from the number itself;
# a key adds legal/trade name, address and status. Free key: gstincheck.co.in
GSTIN_API_KEY = os.getenv("GSTIN_API_KEY", "")
GSTIN_API_URL = os.getenv("GSTIN_API_URL", "https://sheet.gstincheck.co.in/check")
# Provider selection: "gstincheck" (default; free keyed lookups) or "cleartax"
# (unmetered within a ClearTax subscription — use when the firm/CA already
# files through ClearTax; token from the ClearTax account).
GSTIN_PROVIDER = os.getenv("GSTIN_PROVIDER", "gstincheck")
CLEARTAX_HOST = os.getenv("CLEARTAX_HOST", "")
CLEARTAX_AUTH_TOKEN = os.getenv("CLEARTAX_AUTH_TOKEN", "")
CLEARTAX_ENTITY_ID = os.getenv("CLEARTAX_ENTITY_ID", "")
# KnowYourGST: flat-fee plan with unlimited lookups (no per-call metering).
KNOWYOURGST_API_KEY = os.getenv("KNOWYOURGST_API_KEY", "")
KNOWYOURGST_API_URL = os.getenv(
    "KNOWYOURGST_API_URL", "https://www.knowyourgst.com/developers/gstincall/"
)

# AppyFlow: 50 free lookups on signup — the largest free tier available.
APPYFLOW_KEY_SECRET = os.getenv("APPYFLOW_KEY_SECRET", "")
APPYFLOW_API_URL = os.getenv("APPYFLOW_API_URL", "https://appyflow.in/api/verifyGST")

# How long a taxpayer lookup stays cached (default 180 days). Longer = fewer
# metered requests; names/addresses rarely change.
GSTIN_CACHE_SECONDS = int(os.getenv("GSTIN_CACHE_SECONDS", 60 * 60 * 24 * 180))
GEMINI_API_KEYS = os.getenv("GEMINI_API_KEYS", "")
# flash-lite default — ~3s/invoice vs ~15s for full Flash with no
# measurable quality loss on printed invoices. Override per-environment
# via .env for tougher scans. See AIInvoiceProcessor.DEFAULT_MODEL.
GEMINI_VISION_MODEL = os.getenv("GEMINI_VISION_MODEL", "gemini-2.5-flash-lite")
# Ensure log dir exists — django.utils.log.configure_logging will fail to
# attach the FileHandler otherwise (fresh checkouts and CI runners).
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "billing": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
